import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCalculator} from '../reader/calculator.js';import {parseTicket} from '../reader/parser.js';
const read=n=>JSON.parse(fs.readFileSync(`reader/data/${n}.json`));
const stations=read('stations');const calc=createCalculator(read('segments'),stations,read('ordinary_fares_main'),read('ordinary_fares_local'),read('discount_rules'));
const base={from:'札幌',to:'函館',stop:'長万部',price:5020,discount:'student',valid:true};
test('paid ticket price minus used discounted fare',()=>{const r=calc.calculate(base);assert.equal(r.deduction,3170);assert.equal(r.refund,1630);assert.equal(r.unusedInfo.business.toFixed(1),'112.3');assert.equal(calc.calculate({...base,price:5000}).refund,1610);});
test('short used segment forfeits distance discount',()=>{const r=calc.calculate({...base,stop:'小樽',vias:['小樽']});assert.equal(r.usedDiscount,false);assert.equal(r.deduction,r.usedFare);});
test('destination and invalid paths',()=>{assert.equal(calc.calculate({...base,stop:'函館'}).eligible,false);assert.throws(()=>calc.calculate({...base,stop:'旭川'}),/経路上/);assert.throws(()=>calc.calculate({...base,valid:false}),/有効/);assert.throws(()=>calc.calculate({...base,discount:'caregiver_type1'}),/同行/);assert.throws(()=>calc.calculate({...base,passenger:'child'}),/小児/);});
test('six discounts, no balance and ambiguous stop',()=>{for(const r of read('discount_rules').discounts){assert.equal(calc.calculate({...base,discount:r.id,companion:true}).eligible,true);}assert.equal(calc.calculate({...base,price:1}).refund,0);assert.throws(()=>calc.calculate({...base,stop:'札幌',vias:['小樽','札幌']}),/複数回/);});
test('OCR parser handles fullwidth and ambiguous amounts conservatively',()=>{const r=parseTicket('普通乗車券\n札幌 → 函館\n学割\n発売額 ５，０２０円',stations);assert.equal(r.from,'札幌');assert.equal(r.to,'函館');assert.equal(r.price,5020);assert.equal(r.discount,'student');assert.equal(parseTicket('札幌→函館\n5,020円\n2,000円',stations).price,null);assert.equal(parseTicket('障割\n札幌→函館',stations).discount,null);assert.equal(parseTicket('指定席特急券\n札幌→函館',stations).unsupported,true);assert.equal(parseTicket('札幌→函館\n旭川→網走',stations).from,'');});

test('OCR decimal separator and missing arrow',()=>{const r=parseTicket('札幌 つ 函館\n発売額 5.020円',stations);assert.equal(r.price,5020);assert.equal(r.from,'札幌');assert.equal(r.to,'函館');});

import {mergeReadings} from '../reader/parser.js';
import {cleanPixels,frameCrop,ticketBounds} from '../reader/image-processing.js';
test('actual MARS OCR yen symbols and field disagreement',()=>{assert.equal(parseTicket('恵み 野 っ 札幌\n*\\620',stations).price,620);assert.equal(parseTicket('恵み 野 っ 札幌\n*\\620',stations).from,'恵み野');const a=parseTicket('札幌→函館\n*5,020',stations),b=parseTicket('札幌→旭川\n*5,030',stations);const r=mergeReadings([a,b]);assert.equal(r.from,'');assert.equal(r.price,null);assert.equal(mergeReadings([a,parseTicket('入場券',stations)]).unsupported,true);assert.equal(parseTicket('乗車券(かえり)',stations).unsupported,true);});
test('landscape frame crops native video with cover offset',()=>{assert.deepEqual(frameCrop(1920,1080,960,540,{x:160,y:70,w:640,h:400}),{x:320,y:140,w:1280,h:800});const r=frameCrop(1080,1920,960,540,{x:160,y:70,w:640,h:400});assert.equal(r.x,180);assert.equal(r.w,720);assert.ok(r.y>0&&r.y+r.h<=1920);});
test('security pattern threshold, solid ticket crop stays inside image',()=>{const pixels=new Uint8ClampedArray([30,30,30,255,210,220,220,255,180,195,195,255]);const clean=cleanPixels(pixels,3,1);assert.equal(clean[0],0);assert.equal(clean[4],255);const solid=new Uint8ClampedArray(160*100*4);for(let i=0;i<16000;i++)solid.set([180,210,220,255],i*4);const box=ticketBounds(solid,160,100);assert.equal(box.x,0);assert.equal(box.y,0);assert.equal(box.w,1);assert.equal(box.h,1);});
test('yen glyph omitted on standalone fare line, not dates or ambiguous fares',()=>{assert.equal(parseTicket('恵み 野 っ 札幌\n620',stations).price,620);assert.equal(parseTicket('19.-5.22\n30003-01\nC56',stations).price,null);assert.equal(parseTicket('620\n3200',stations).price,null);});

import {classifyTicket} from '../reader/ticket-kind.js';
test('limited express and green ticket titles, combined ticket and spaced OCR',()=>{
 for(const title of ['指定席特急券','自由席特急券','特 急 券','特急\n券'])assert.equal(classifyTicket(title).id,'limited_express');
 assert.equal(classifyTicket('自由席特急券').seat,'unreserved');assert.equal(classifyTicket('指定席特急券').seat,'reserved');
 assert.equal(classifyTicket('グ リ ー ン 券').id,'green');assert.equal(classifyTicket('グリーン\n券').id,'green');
 for(const title of ['特急券・グリーン券','特急・グリーン券','特急券(グリーン)'])assert.equal(classifyTicket(title).id,'limited_express+green');
 assert.equal(classifyTicket('乗車券・特急券・グリーン券').id,'ordinary+limited_express+green');assert.equal(classifyTicket('乗車券・特急券').calculable,false);
 assert.equal(classifyTicket('指定料金券').id,'seat_fee');assert.equal(classifyTicket('不鮮明な文字').id,'unknown');
});
test('instructions mentioning express or green tickets do not reclassify ordinary title',()=>{const r=classifyTicket('乗車券\n札幌→函館\n特急券は別途お求めください\nグリーン券が必要な場合があります');assert.equal(r.id,'ordinary');assert.equal(r.calculable,true);});
test('partial combined title and contradictory ticket types',()=>{const p=t=>parseTicket(t,stations);assert.equal(mergeReadings([p('乗車券・特急券'),p('特急券')]).ticketKind.id,'ordinary+limited_express');const r=mergeReadings([p('特急券'),p('グリーン券')]);assert.equal(r.ticketKind.id,'conflict');assert.equal(r.unsupported,true);assert.equal(mergeReadings([p('特急券'),p('読めない')]).ticketKind.id,'limited_express');});
test('real fee-ticket instruction OCR is not classified as an express title',()=>{const r=classifyTicket('生\n東室蘭 っ 札幌\n指定料多券とお千持ちの特急券は指定別車に限り有効\nです。お手持ちの乗車券等と同時にご利用の場合に限って有効です。\n510');assert.equal(r.id,'unknown');assert.equal(classifyTicket('グリー\nン券').id,'green');});

import {assembleLines} from '../reader/ocr-lines.js';
test('real AI detections join spaced station names without nearby instruction lines',()=>{const a=(text,x,y,w,h,score=.95)=>({text,score,poly:[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]});const raw=assembleLines([a('恵み野',109,242,290,91),a('→札幌',384,258,414,89),a('经由：千歲線',114,322,250,40),a('¥620',736,374,108,48),a('不確かな文字',0,400,100,30,.4)]);const p=parseTicket(raw,stations);assert.equal(p.from,'恵み野');assert.equal(p.to,'札幌');assert.equal(p.price,620);assert.ok(!raw.includes('不確か'));});
test('child alternative fare is not evidence of a child ticket; uncertain money and city tickets are held',()=>{assert.equal(parseTicket('乗車券\n小児180円',stations).passenger,null);assert.equal(parseTicket('乗車券\n小\n620円',stations).passenger,'child');assert.equal(parseTicket('乗車券\n360元\n小児180円',stations).price,null);assert.equal(parseTicket('乗車券\n札幌市内→函館',stations).unsupported,false);assert.equal(parseTicket('乗車券\n¥620\n2025.-8.14元きねっと',stations).price,620);});
test('combined ticket recognized from explicit fare breakdown',()=>{assert.equal(classifyTicket('不鮮明な券名\n内訳：乗5.610·特2.690').id,'ordinary+limited_express');});

import {priceBand,recoveredMoney} from '../reader/ocr-lines.js';
test('price recovery rejects serials, uncertain currency and weak OCR',()=>{assert.equal(recoveredMoney([{text:'￥170',score:.9},{text:'￥1706',score:.99},{text:'2203',score:.99},{text:'話220',score:.99},{text:'￥220',score:.8}]),'¥170');assert.equal(recoveredMoney([{text:'￥3,250',score:.95}]),'¥3,250');assert.equal(priceBand([],800,500),null);const r=priceBand([{text:'1日間有効',score:.95,poly:[[50,100],[300,100],[300,125],[50,125]]},{text:'012345',score:.9,poly:[[700,100],[710,100],[710,300],[700,300]]}],800,500);assert.ok(r.x>300&&r.x+r.w<=700&&r.y+r.h<=500);});

import {isHeicPhoto} from '../reader/photo-loader.js';
test('HEIC detection uses file header, not filename or MIME alone',async()=>{const heic=new Blob([new Uint8Array([0,0,0,24]),'ftypheic',new Uint8Array(12)]);assert.equal(await isHeicPhoto(heic),true);assert.equal(await isHeicPhoto(new Blob(['not an image'],{type:'image/heic'})),false);assert.equal(await isHeicPhoto(new Blob(['\xff\xd8jpeg'])),false);});
test('explicit express and green breakdown must add up to the total',()=>{const text='特急券・グリーン券\n札幌→函館\n￥3,300 内訳：特1,210·グ2.090';const r=parseTicket(text,stations);assert.deepEqual(r.fees,{limited_express:1210,green:2090});assert.equal(r.ticketKind.id,'limited_express+green');assert.equal(r.unsupported,true);assert.equal(parseTicket(text.replace('2.090','2.080'),stations).fees,null);assert.equal(parseTicket(text.replace('1,210','I,210'),stations).fees,null);assert.equal(parseTicket(text.replace('内訳：','北斗20号 '),stations).fees,null);const conflict=parseTicket(text.replace('1,210','1,200').replace('2.090','2.100'),stations);assert.equal(mergeReadings([r,conflict]).fees,null);assert.equal(mergeReadings([r,parseTicket('特急券・グリーン券',stations)]).fees.green,2090);});

import {createCancellationCalculator,suggestedVias,supportsCancellation} from '../reader/cancellation.js';
const cancellation=createCancellationCalculator(calc,stations),greenKind={kinds:['limited_express','green'],label:'特急券＋グリーン券'},greenInput={kind:greenKind,mode:'normal',from:'札幌',to:'長万部',stop:'苫小牧',vias:['南千歳','東室蘭'],price:3300,components:{limited_express:1210,green:2090},started:true,valid:true};
test('normal and interrupted express/green travel have different refund bases',()=>{assert.equal(cancellation(greenInput).refund,0);assert.equal(cancellation(greenInput).fee,0);const input={...greenInput,mode:'accident',purchasedBefore:true,unavailable:{limited_express:'yes',green:'yes'}};const r=cancellation(input);assert.equal(r.refund,3300);assert.equal(r.fee,0);assert.equal(cancellation({...input,unavailable:{limited_express:'yes',green:'no'}}).refund,1210);assert.equal(cancellation({...input,stop:'長万部',unavailable:{}}).refund,0);assert.ok(r.path.some(s=>s.to==='苫小牧'));});
test('cancellation rejects uncertain eligibility and inconsistent combined amounts',()=>{assert.throws(()=>cancellation({...greenInput,mode:'accident'}),/購入/);assert.throws(()=>cancellation({...greenInput,mode:'accident',purchasedBefore:true}),/確認/);assert.throws(()=>cancellation({...greenInput,started:false}),/使用/);assert.throws(()=>cancellation({...greenInput,components:{limited_express:1210,green:2000}}),/合計/);assert.throws(()=>cancellation({...greenInput,stop:'小樽'}),/経路/);assert.throws(()=>cancellation({...greenInput,kind:{...greenKind,restricted:true}}),/対象外/);assert.equal(supportsCancellation(parseTicket('団体乗車券',stations).ticketKind),false);assert.equal(supportsCancellation(parseTicket('乗車券\n札幌市内→函館',stations).ticketKind),true);});
test('ordinary cancellation keeps normal calculation and accident discounts regardless of unused distance',()=>{const input={...base,kind:{kinds:['ordinary'],label:'普通乗車券'},mode:'normal',started:true,passenger:'adult'};assert.equal(cancellation(input).refund,calc.calculate(base).refund);const a=cancellation({...input,mode:'accident',purchasedBefore:true,stop:'五稜郭'});const fare=calc.fare(a.unusedInfo.table,a.unusedInfo.km,'adult');assert.equal(a.refund,Math.min(input.price,Math.ceil(fare*.8/10)*10));assert.ok(a.unusedInfo.business<101);assert.equal(a.fee,0);assert.throws(()=>cancellation({...input,stop:'小樽',mode:'accident',purchasedBefore:true,discount:'caregiver_type1'}),/同行|経路/);});
test('mixed ordinary/fee ticket uses only the paid fare component for normal cancellation',()=>{const input={...base,kind:{kinds:['ordinary','limited_express','green'],label:'一体券'},mode:'normal',started:true,passenger:'adult',price:8320,components:{ordinary:5020,limited_express:1210,green:2090}};const r=cancellation(input);assert.equal(r.refund,calc.calculate(base).refund);assert.equal(r.rows[0].paid,5020);assert.equal(r.rows[1].refund,0);assert.equal(r.fee,220);});
test('Hokuto route hints follow the ticket direction and never guess other train routes',()=>{assert.equal(parseTicket('特急券・グリーン券\n札幌→長万部\n北斗20号\n￥3,300',stations).train,'北斗');assert.deepEqual(suggestedVias('北斗','札幌','長万部',calc),['南千歳','東室蘭']);assert.deepEqual(suggestedVias('北斗','長万部','札幌',calc),['東室蘭','南千歳']);assert.deepEqual(suggestedVias('北斗','東室蘭','函館',calc),[]);assert.deepEqual(suggestedVias(null,'札幌','長万部',calc),[]);});

// City fare calculation must change at the shortened segment's 200km boundary.
test('Sapporo city: OCR metadata, short used actual origin and long used central origin',()=>{
 const parsed=parseTicket('乗車券\n札幌（市内）→函館\n8,000円',stations);assert.equal(parsed.from,'札幌');assert.equal(parsed.ticketKind.city.from,true);
 const input={kind:parsed.ticketKind,city:{from:true},actualFrom:'手稲',from:'札幌',to:'函館',stop:'小樽',vias:['小樽'],price:8000,mode:'normal',discount:'none',passenger:'adult',started:true,valid:true};
 const short=cancellation(input);assert.equal(short.rows[0].ordinary.deduction,calc.fare(calc.totals(calc.route('手稲','小樽',[])).table,calc.totals(calc.route('手稲','小樽',[])).km,'adult'));assert.match(short.cityContext.basis,/実際/);
 const long=cancellation({...input,stop:'八雲'});assert.match(long.cityContext.basis,/中心駅/);assert.equal(long.rows[0].ordinary.deduction,calc.calculate({...input,stop:'八雲'}).deduction);
 assert.throws(()=>cancellation({...input,actualFrom:'小樽'}),/実際/);assert.throws(()=>cancellation({...input,stop:'手稲'}),/発側/);assert.throws(()=>cancellation({...input,to:'旭川',stop:'岩見沢',vias:[]}),/200km/);
});
test('Sapporo city destination accident uses centre, city bounds and restricted products stay blocked',()=>{
 const kind=parseTicket('乗車券\n函館→札幌市内',stations).ticketKind;
 const input={kind,city:{to:true},actualTo:'手稲',from:'函館',to:'札幌',stop:'長万部',vias:['東室蘭','南千歳'],price:8000,mode:'accident',discount:'none',passenger:'adult',started:true,valid:true,purchasedBefore:true};
 const r=cancellation(input), info=calc.totals(calc.route('長万部','札幌',['東室蘭','南千歳']));
 assert.equal(r.unusedInfo.business,info.business);assert.equal(r.rows[0].refund,calc.fare(info.table,info.km,'adult'));
 assert.throws(()=>cancellation({...input,stop:'札幌'}),/着側/);
 assert.equal(supportsCancellation(parseTicket('乗車券\n東京都区内→函館',stations).ticketKind),false);
 assert.equal(supportsCancellation(parseTicket('トクだ值35（乗車券つき）\n乗車券・特急券\n札幌（市内）→網走',stations).ticketKind),false);
 assert.equal(mergeReadings([parseTicket('乗車券\n札幌市内→函館',stations),parseTicket('乗車券\n札幌→函館',stations)]).ticketKind.city.from,true);
});

test('seat classification auto-fills only explicit seat evidence and withholds conflicts',()=>{const a=parseTicket('特急券・グリーン券\n札幌→長万部\n1号車5番D席\n3,300円',stations);assert.equal(a.chargeSeat,'reserved');assert.equal(parseTicket('特急券\n札幌→函館',stations).chargeSeat,null);assert.equal(parseTicket('座席未指定券\n特急券',stations).chargeSeat,'unassigned');assert.equal(mergeReadings([a,parseTicket('自由席特急券',stations)]).chargeSeat,null);});
