import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCalculator} from '../reader/calculator.js';import {createReaderRefundCalculator} from '../reader/before-refund.js';
const read=n=>JSON.parse(fs.readFileSync(`reader/data/${n}.json`)),stations=read('stations');
const calc=createCalculator(read('segments'),stations,read('ordinary_fares_main'),read('ordinary_fares_local'),read('discount_rules')),refund=createReaderRefundCalculator(calc,stations);
const kind=(...kinds)=>({kinds,seat:'unknown'}),base={kind:kind('ordinary'),usage:'before',mode:'normal',from:'札幌',to:'函館',price:8000,unused:true,valid:true};
const reserved={...base,kind:kind('limited_express'),price:3300,chargeSeat:'reserved',requestDate:'2026-10-04T10:00',departureDate:'2026-10-06T08:00',changedLate:'no'};
test('unused fare: paid discounted price, no distance or stop condition; eligibility is explicit',()=>{assert.equal(refund(base).refund,7780);assert.equal(refund({...base,price:100,from:'札幌',to:'苗穂'}).refund,0);assert.equal(refund({...base,city:{from:true}}).refund,7780);assert.throws(()=>refund({...base,unused:false}),/未使用/);assert.throws(()=>refund({...base,valid:false}),/有効/);assert.throws(()=>refund({...base,kind:{...base.kind,restricted:true}}),/対象外/);assert.throws(()=>refund({...base,usage:''}),/開始前/);});
test('reserved calendar dates in Japan: two days before, previous day, deadline and changed tickets',()=>{assert.equal(refund(reserved).fee,340);assert.equal(refund({...reserved,requestDate:'2026-10-05T00:00'}).fee,990);assert.equal(refund({...reserved,changedLate:'yes'}).fee,990);assert.equal(refund({...reserved,price:1210,requestDate:'2026-10-05T00:00'}).fee,360);assert.equal(refund({...reserved,price:1000,requestDate:'2026-10-05T00:00'}).fee,340);assert.throws(()=>refund({...reserved,requestDate:'2026-10-06T08:00'}),/出発/);assert.throws(()=>refund({...reserved,requestDate:'2026-02-30T00:00'}),/正しく/);assert.throws(()=>refund({...reserved,changedLate:''}),/変更/);assert.throws(()=>refund({...reserved,chargeSeat:''}),/座席/);});
test('free, standing and unassigned fee tickets',()=>{assert.equal(refund({...reserved,chargeSeat:'unreserved',requestDate:''}).fee,220);assert.equal(refund({...reserved,chargeSeat:'standing'}).fee,220);assert.equal(refund({...reserved,chargeSeat:'unassigned',requestDate:''}).fee,340);assert.equal(refund({...reserved,kind:kind('green'),chargeSeat:'unreserved'}).fee,220);assert.throws(()=>refund({...reserved,kind:kind('green'),chargeSeat:'unassigned'}),/グリーン/);});
test('express/green joint ticket charges only the green component; ordinary adds its own fee',()=>{const joint={...reserved,kind:kind('limited_express','green'),price:3300,components:{limited_express:1210,green:2090}};assert.equal(refund(joint).fee,340);const late=refund({...joint,requestDate:'2026-10-05T12:00'});assert.equal(late.fee,620);assert.equal(late.refund,2680);assert.equal(late.rows[0].fee,0);assert.equal(refund({...joint,kind:kind('ordinary','limited_express','green'),price:8300,components:{ordinary:5000,limited_express:1210,green:2090}}).fee,560);assert.throws(()=>refund({...joint,components:{limited_express:1200,green:2090}}),/内訳/);});
test('before accident: full refund only with explicit purchase/cancellation/unavailable checks',()=>{const incident={...base,mode:'accident',purchasedBefore:true,tripCancelled:true};assert.equal(refund(incident).refund,8000);assert.equal(refund(incident).fee,0);assert.throws(()=>refund({...incident,purchasedBefore:false}),/事由/);assert.throws(()=>refund({...incident,tripCancelled:false}),/旅行/);const joint={...incident,kind:kind('limited_express','green'),price:3300,components:{limited_express:1210,green:2090},unavailable:{limited_express:'yes',green:'yes'}};assert.equal(refund(joint).refund,3300);assert.throws(()=>refund({...joint,unavailable:{limited_express:'yes',green:'no'}}),/グリーン/);});
test('after wrapper retains normal cancellation and does not turn missing usage into unused refund',()=>{const r=refund({...base,usage:'after',started:true,stop:'長万部',discount:'none',passenger:'adult',vias:['南千歳','東室蘭']});assert.equal(r.refund,2940);assert.equal(r.usage,'after');assert.throws(()=>refund({...base,usage:undefined}),/選択/);});

test('quick timing choices preserve fees and never accept the passed departure or missing choice',()=>{const joint={...reserved,kind:kind('limited_express','green'),price:3300,components:{limited_express:1210,green:2090},requestDate:undefined,departureDate:undefined,changedLate:undefined};assert.equal(refund({...joint,timingBand:'early'}).fee,340);assert.equal(refund({...joint,timingBand:'late'}).fee,620);assert.equal(refund({...joint,timingBand:'changed'}).fee,620);assert.throws(()=>refund({...joint,timingBand:'departed'}),/出発/);assert.throws(()=>refund({...joint,timingBand:''}),/時期/);});
